repos:
-   repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
    -   id: black
        exclude: ^(database/alembic/|database/data/|tests/data/|.*\.properties$)

- repo: https://github.com/PyCQA/flake8
  rev: 6.1.0
  hooks:
  - id: flake8
    args: [--max-line-length=120]
    exclude: ^(database/alembic/|database/data/|tests/data/|.*\.properties$)

- repo: local
  hooks:
    - id: pytest
      name: pytest
      entry: bash -c 'PYTHONPATH=.' pytest
      language: system
      types: [ python ]
      include: ^tests/.*\.py$
      args: [ --maxfail=1, --disable-warnings, -q ]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-yaml
    -   id: check-added-large-files
